### ISSUE TITLE
New Server for Ice Jams Services

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/IceJamsservices#1]
Need a place to deploy .Net Core services for the Ice Jams project.
We're thinking a smallish Windows EC2, auto-shutdown every night.
Should be in the WMA sub-account.

This server could also serve as a test instance for .NetCore STN services in the future.

**Comment by aaronstephenson** [comment]
Rather than an EC2 instance, we have decided to try ECS. I have set up the necessary users, roles, and other permissions and will send Jeremy and Lauren their credentials via email.
